name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.0
          - 3.1
          - 3.2
          - head
        rails-version:
          - 6-1
          - 7-0
          - 8-0
          - main
        include:
          - ruby-version: head
            rails-version: 8-0
            continue-on-error: true
          - ruby-version: head
            rails-version: main
            continue-on-error: true
        exclude:
          - { ruby-version: head, rails-version: 6-1 }
          - { ruby-version: head, rails-version: 7-0 }
          - { ruby-version: 3.0, rails-version: 8-0 }
          - { ruby-version: 3.1, rails-version: 8-0 }
          - { ruby-version: 3.1, rails-version: main }
    env:
      BUNDLE_GEMFILE: "gemfiles/Gemfile-rails-${{ matrix.rails-version }}"

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
          cache-version: 3
      - run: bundle exec rake test

  test-integration:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby-version:
          - 3.0
          - 3.1
          - 3.2
          - head
        rails-version:
          - 6-1
          - 7-0
          - 8-0
          - main
        include:
          - ruby-version: head
            rails-version: 8-0
            continue-on-error: true
          - ruby-version: head
            rails-version: main
            continue-on-error: true
        exclude:
          - { ruby-version: 3.0, rails-version: 8-0 }
          - { ruby-version: 3.1, rails-version: 8-0 }
          - { ruby-version: 3.1, rails-version: main }
    env:
      BUNDLE_GEMFILE: "gemfiles/Gemfile-rails-${{ matrix.rails-version }}"

    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "${{ matrix.ruby-version }}"
          bundler-cache: true
          cache-version: 3
      - run: bundle exec rake test:integration

  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true
      - run: bundle exec rubocop
